/**
 * Grave palette.
 *
 * Everything here derives from two sets of master tokens:
 *
 * 1. Grave neutrals — the warm gray ramp provided by Grave. The stops that
 *    were not provided (020/060/080 and 920-1040) are warm interpolations of
 *    the neighboring Grave stops, never cool Pierre grays.
 * 2. Hue anchors — one muted "500" master per hue, tuned for the warm
 *    neutrals. Inspiration: Kanagawa Dragon, Gruvbox Material, Kanso, and
 *    base16 Black Metal (Gorgoroth) restraint; ramp structure from Pierre.
 *
 * Each chromatic ramp is generated by mixing its anchor toward the Grave
 * warm white (gray 040) for light stops and the Grave warm black (gray 1000)
 * for dark stops, so every derived color stays in the same warm key.
 */

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function rgbToHex(r: number, g: number, b: number): string {
  const c = (v: number) => Math.round(Math.min(255, Math.max(0, v))).toString(16).padStart(2, "0");
  return `#${c(r)}${c(g)}${c(b)}`;
}

/** Linear sRGB-space mix of `a` toward `b` by `t` (0..1). */
function mix(a: string, b: string, t: number): string {
  const [ar, ag, ab] = hexToRgb(a);
  const [br, bg, bb] = hexToRgb(b);
  return rgbToHex(ar + (br - ar) * t, ag + (bg - ag) * t, ab + (bb - ab) * t);
}

// Grave master neutrals (provided stops marked). Non-provided stops are warm
// interpolations between the neighboring Grave masters.
const gray = {
  "020": "#fdfdfc",
  "040": "#FAFAF9", // Grave provided
  "060": "#f8f8f7",
  "080": "#f7f6f5",
  "100": "#F5F5F4", // Grave provided
  "200": "#E7E7E7", // Grave provided
  "300": "#D6D4D4", // Grave provided
  "400": "#A8A4A2", // Grave provided
  "500": "#777370", // Grave provided
  "600": "#565451", // Grave provided
  "700": "#44413F", // Grave provided
  "800": "#272625", // Grave provided
  "900": "#1C1A18", // Grave provided
  "920": "#191715",
  "940": "#161412",
  "960": "#121010",
  "980": "#0f0d0d",
  "1000": "#0C0A0A", // Grave provided (from your 950 stop)
  "1020": "#090808",
  "1040": "#070606",
};

const warmWhite = gray["040"];
const warmBlack = gray["1000"];

type Ramp = {
  "050": string;
  "100": string;
  "200": string;
  "300": string;
  "400": string;
  "500": string;
  "600": string;
  "700": string;
  "800": string;
  "900": string;
  "950": string;
};

/** Derive a full 050-950 ramp from a single muted master anchor (the 500). */
function ramp(anchor: string): Ramp {
  return {
    "050": mix(anchor, warmWhite, 0.92),
    "100": mix(anchor, warmWhite, 0.84),
    "200": mix(anchor, warmWhite, 0.66),
    "300": mix(anchor, warmWhite, 0.44),
    "400": mix(anchor, warmWhite, 0.22),
    "500": anchor,
    "600": mix(anchor, warmBlack, 0.18),
    "700": mix(anchor, warmBlack, 0.34),
    "800": mix(anchor, warmBlack, 0.5),
    "900": mix(anchor, warmBlack, 0.65),
    "950": mix(anchor, warmBlack, 0.78),
  };
}

// Muted hue anchors. Sources of inspiration per hue:
// Kanagawa Dragon (red/orange/yellow/green/blue/indigo/pink/mint),
// Gruvbox Material (teal), Kanagawa oniViolet (purple), earthy Gruvbox brown.
const red = ramp("#c4746e");
const orange = ramp("#b6927b");
const yellow = ramp("#c4b28a");
const green = ramp("#87a987");
const mint = ramp("#8ea4a2");
const teal = ramp("#7daea3");
const cyan = ramp("#7fb4ca");
const blue = ramp("#8ba4b0");
const indigo = ramp("#8992a7");
const purple = ramp("#957fb8");
const pink = ramp("#a292a3");
// Kept for parity with the Pierre baseline; not wired into roles yet.
export const brown = ramp("#a08264");

export type Roles = {
  bg: { editor: string; window: string; inset: string; elevated: string };
  fg: { base: string; fg1: string; fg2: string; fg3: string; fg4: string };
  border: {
    window: string;
    editor: string;
    indentGuide: string;
    indentGuideActive: string;
    inset: string;
    elevated: string;
  };
  accent: { primary: string; link: string; subtle: string; contrastOnAccent: string };
  states: { merge: string; success: string; danger: string; warn: string; info: string };
  syntax: {
    comment: string;
    string: string;
    number: string;
    keyword: string;
    regexp: string;
    func: string;
    type: string;
    variable: string;
    operator: string;
    punctuation: string;
    constant: string;
    parameter: string;
    namespace: string;
    decorator: string;
    escape: string;
    invalid: string;
    tag: string;
    attribute: string;
  };
  ansi: {
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
    brightBlack: string;
    brightRed: string;
    brightGreen: string;
    brightYellow: string;
    brightBlue: string;
    brightMagenta: string;
    brightCyan: string;
    brightWhite: string;
  };
};

export const light: Roles = {
  bg: {
    editor: gray["020"],
    window: gray["060"],
    inset: gray["080"],
    elevated: gray["040"],
  },
  fg: {
    base: gray["1040"],
    fg1: gray["900"],
    fg2: gray["800"],
    fg3: gray["600"],
    fg4: gray["500"],
  },
  border: {
    window: gray["100"],
    editor: gray["200"],
    indentGuide: gray["100"],
    indentGuideActive: gray["200"],
    inset: gray["200"],
    elevated: gray["100"],
  },
  accent: {
    primary: blue["600"],
    link: blue["600"],
    subtle: blue["100"],
    contrastOnAccent: gray["1000"], // dark ink on muted accents, like the dark theme
  },
  states: {
    merge: indigo["600"],
    success: mint["600"],
    danger: red["600"],
    warn: yellow["600"],
    info: cyan["600"],
  },
  syntax: {
    comment: gray["500"],
    string: green["700"],
    number: cyan["700"],
    keyword: pink["700"],
    regexp: teal["700"],
    func: indigo["700"],
    type: purple["700"],
    variable: orange["700"],
    operator: cyan["600"],
    punctuation: gray["700"],
    constant: yellow["700"],
    parameter: gray["700"],
    namespace: yellow["700"],
    decorator: blue["700"],
    escape: cyan["700"],
    invalid: red["700"],
    tag: red["700"],
    attribute: mint["700"],
  },
  ansi: {
    black: gray["900"],
    red: red["600"],
    green: green["600"],
    yellow: yellow["600"],
    blue: blue["600"],
    magenta: purple["600"],
    cyan: cyan["600"],
    white: gray["300"],
    brightBlack: gray["600"],
    brightRed: red["500"],
    brightGreen: green["500"],
    brightYellow: yellow["500"],
    brightBlue: blue["500"],
    brightMagenta: purple["500"],
    brightCyan: cyan["500"],
    brightWhite: gray["100"],
  },
};

export const dark: Roles = {
  bg: {
    editor: gray["1040"],
    window: gray["1000"],
    inset: gray["980"],
    elevated: gray["1020"],
  },
  fg: {
    base: gray["020"],
    fg1: gray["200"],
    fg2: gray["400"],
    fg3: gray["600"],
    fg4: gray["700"],
  },
  border: {
    window: gray["1040"],
    editor: gray["980"],
    indentGuide: gray["980"],
    indentGuideActive: gray["960"],
    inset: gray["980"],
    elevated: gray["980"],
  },
  accent: {
    primary: blue["500"],
    link: blue["500"],
    subtle: blue["950"],
    contrastOnAccent: gray["1040"],
  },
  states: {
    merge: indigo["500"],
    success: mint["500"],
    danger: red["500"],
    warn: yellow["500"],
    info: cyan["500"],
  },
  syntax: {
    comment: gray["600"],
    string: green["400"],
    number: cyan["400"],
    keyword: pink["400"],
    regexp: teal["400"],
    func: indigo["400"],
    type: purple["400"],
    variable: orange["400"],
    operator: cyan["500"],
    punctuation: gray["700"],
    constant: yellow["400"],
    parameter: gray["400"],
    namespace: yellow["500"],
    decorator: blue["400"],
    escape: cyan["400"],
    invalid: red["400"],
    tag: red["400"],
    attribute: mint["400"],
  },
  ansi: {
    black: gray["1000"],
    red: red["500"],
    green: green["500"],
    yellow: yellow["500"],
    blue: blue["500"],
    magenta: purple["500"],
    cyan: cyan["500"],
    white: gray["300"],
    brightBlack: gray["600"],
    brightRed: red["400"],
    brightGreen: green["400"],
    brightYellow: yellow["400"],
    brightBlue: blue["400"],
    brightMagenta: purple["400"],
    brightCyan: cyan["400"],
    brightWhite: gray["100"],
  },
};
